### PR TITLE
first commit delong_test

### PR DESCRIPTION
**Pull request by gpucce**
Here is the starting pull request, indeed the way you implement roc does not really matter since one needs to compute from tar, nontar anyway, I will add documentation to the functions, though I don't really know what to write. I also add a [link](https://statisticaloddsandends.wordpress.com/2020/06/07/what-is-the-delong-test-for-comparing-aucs/) to an explanation of what the test is supposed to do. 

If you think this is not useful or anything just delete it or if it needs strong changes tell me I am happy to try to do it.

### CODE REVIEW

**Comment by davidavdav** [comment]
OK, thanks, perhaps add a couple of test cases, which are useful if we change the coding style a little here and there, to make sure we're still doing the right thing

**Comment by gpucce** [comment]
Sure I will, I started very enthusiastic but then work kicked in xD in the next days I'll add the tests.

**Comment by gpucce** [comment]
Tests added!! Let me know if they are enough.

**Comment by davidavdav** [comment]
In github I see a few files that end without a newline, could you add these please?

**Pull request merged**
